export const DELEGATIONS = [
  "2Pac",
  "Suge Knight",
  "David Kenner",
  "Snoop Dogg",
  "Dr. Dre",
  "Ice Cube",
  "Kurupt",
  "Treach",
  "Mob James",
  "B-Legit",
  "E-40",
  "Yaki Kadafi",
  "Frank Alexander",
  "Biggie Smalls",
  "Puff Daddy",
  "Jay-Z",
  "Nas",
  "Lil' Kim",
  "Prodigy",
  "Busta Rhymes",
  "Jimmy Henchman",
  "Haitian Jack",
  "Method Man",
  "Raekwon",
  "Funkmaster Flex",
] as const;

export type DelegationName = (typeof DELEGATIONS)[number];
